#
# Docker Compose for local developing
#
# Purpose:
#   During the local developing, the backends needs the "db", "db-admin" and "queue" services
#
#   - "db"        the mariadb database server
#   - "db-admin"  the phpMyAdmin frontend for the mariadb server
#   - "queue"     The redis server for communication between the backend applications
#
# IMPORTANT:
#   DON'T use this docker-compose file on PRODUCTION
#
version: '3.8'

services:
  #
  # Service "db" (MariaDB)
  #
  db:
    image: mariadb:latest
    container_name: blueskyfish_whalerider_database
    restart: unless-stopped
    ports:
      - "52306:3306"
    volumes:
      - ../var/mariadb-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=blueskyfish1234
    networks:
      - develop_net

  #
  # Service PhpMyAdmin as "db-admin" for access to "db"
  #
  db-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: blueskyfish_whalerider_admin
    restart: unless-stopped
    ports:
      - "52008:80"
    links:
      - db:db
    networks:
      - develop_net
    depends_on:
      - db

  #
  # service "Queue" (Redis)
  queue:
    image: redis:latest
    container_name: blueskyfish_whalerider_queue
    restart: unless-stopped
    ports:
      - "52379:6379"
    networks:
      - develop_net

networks:
  develop_net:
    driver: bridge

